export { TournamentsListPage } from "./TournamentsListPage"
export { AboutPage } from "./AboutPage"
export { NotFoundPage } from "./NotFoundPage"
export { TournamentPage } from "./TournamentPage"
export { LoginPage } from "./LoginPage"
export { RegisterPage } from "./RegisterPage"
