export { TournamentsListPage } from "./TournamentsListPage"
export { AboutPage } from "./AboutPage"
export { NotFoundPage } from "./NotFoundPage"
export { TournamentPage } from "./TournamentPage"
export { LoginPage } from "./LoginPage"
export { RegisterPage } from "./RegisterPage"
export { CreateTournamentPage } from "./CreateTournamentPage"
export { EditTournamentPage as EditPage } from "./EditTournamentPage"
export { ProfilePage } from "./ProfilePage"
export { LeaderboardPage } from "./LeaderboardPage"
